"use client";

// ShaderBackground — generated by the 21st.dev Shader Builder ("Silk")
// High-performance WebGL GLSL fluid wave shader background adapted for CodeBeast AI

import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";

const VERT = `attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}`;


const FRAG = `#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec3 u_colors[8];
// Seven packed vectors + eight colour vectors = 15 fragment uniform vectors,
// one below WebGL1's guaranteed minimum. Macros preserve the public u_* API.
uniform vec4 u_scene;      // resolution.xy, time, colour count
uniform vec4 u_shape;      // scale, intensity, paramA, warp
uniform vec4 u_surface;    // detail, contrast, brightness, saturation
uniform vec4 u_finish;     // hue, vignette, blur, grain
uniform vec4 u_transform;  // seed, rotation, drift, OKLab toggle
uniform vec4 u_space;      // offset.xy, pointer.xy
uniform vec4 u_cursor;

#define u_resolution u_scene.xy
#define u_time u_scene.z
#define u_colorCount u_scene.w
#define u_scale u_shape.x
#define u_intensity u_shape.y
#define u_paramA u_shape.z
#define u_warp u_shape.w
#define u_detail u_surface.x
#define u_contrast u_surface.y
#define u_brightness u_surface.z
#define u_saturation u_surface.w
#define u_hue u_finish.x
#define u_vignette u_finish.y
#define u_blur u_finish.z
#define u_grain u_finish.w
#ifdef GL_FRAGMENT_PRECISION_HIGH
#define u_seed u_transform.x
#else
// Keep hash inputs inside mediump's guaranteed ±2^14 range.
#define u_seed mod(u_transform.x, 31.0)
#endif
#define u_rotate u_transform.y
#define u_drift u_transform.z
#define u_oklab u_transform.w
#define u_offset u_space.xy
#define u_mouse u_space.zw
#define u_cursorPresence u_cursor.x
#define u_cursorEffect u_cursor.y
#define u_cursorStrength u_cursor.z
#define u_cursorRadius u_cursor.w

float hash21(vec2 p) {
#ifndef GL_FRAGMENT_PRECISION_HIGH
  p = mod(p, 31.0);
#endif
  p = fract(p * vec2(234.34, 435.345));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

// Even, un-structured white noise for film grain (Dave Hoskins hash12).
float grainHash(vec2 p) {
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

vec2 hash22(vec2 p) {
#ifndef GL_FRAGMENT_PRECISION_HIGH
  p = mod(p, 31.0);
#endif
  float n = sin(dot(p, vec2(41.0, 289.0)));
  return fract(vec2(15731.743, 7892.321) * n);
}

float noise(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(
    mix(hash21(i), hash21(i + vec2(1.0, 0.0)), u.x),
    mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), u.x),
    u.y);
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p = p * 2.03 + vec2(17.0, 9.2);
    a *= 0.5;
  }
  return v;
}

// --- OKLab colour mixing (perceptual), gated by u_oklab -----------------------
vec3 srgbToLinear(vec3 c) {
  return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)),
    step(0.04045, c));
}
vec3 linearToSrgb(vec3 c) {
  return mix(c * 12.92, 1.055 * pow(max(c, vec3(0.0)), vec3(1.0 / 2.4)) - 0.055,
    step(0.0031308, c));
}
vec3 linToOklab(vec3 c) {
  float l = 0.4122214708 * c.r + 0.5363325363 * c.g + 0.0514459929 * c.b;
  float m = 0.2119034982 * c.r + 0.6806995451 * c.g + 0.1073969566 * c.b;
  float s = 0.0883024619 * c.r + 0.2817188376 * c.g + 0.6299787005 * c.b;
  l = pow(max(l, 0.0), 1.0 / 3.0);
  m = pow(max(m, 0.0), 1.0 / 3.0);
  s = pow(max(s, 0.0), 1.0 / 3.0);
  return vec3(
    0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s);
}
vec3 oklabToLin(vec3 c) {
  float l = c.x + 0.3963377774 * c.y + 0.2158037573 * c.z;
  float m = c.x - 0.1055613458 * c.y - 0.0638541728 * c.z;
  float s = c.x - 0.0894841775 * c.y - 1.2914855480 * c.z;
  l = l * l * l; m = m * m * m; s = s * s * s;
  return vec3(
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s);
}
vec3 mixColour(vec3 a, vec3 b, float t) {
  if (u_oklab > 0.5) {
    vec3 la = linToOklab(srgbToLinear(a));
    vec3 lb = linToOklab(srgbToLinear(b));
    return clamp(linearToSrgb(oklabToLin(mix(la, lb, t))), 0.0, 1.0);
  }
  return mix(a, b, t);
}

// Mix through the recipe colours; x is clamped to 0..1.
vec3 palette(float x) {
  float n = max(u_colorCount - 1.0, 1.0);
  float f = clamp(x, 0.0, 1.0) * n;
  vec3 col = u_colors[0];
  for (int i = 0; i < 7; i++) {
    if (float(i) < n)
      col = mixColour(col, u_colors[i + 1],
        smoothstep(0.0, 1.0, clamp(f - float(i), 0.0, 1.0)));
  }
  return col;
}

vec3 hueRotate(vec3 col, float a) {
  const mat3 toYIQ = mat3(0.299, 0.596, 0.211,
                          0.587, -0.274, -0.523,
                          0.114, -0.322, 0.312);
  const mat3 toRGB = mat3(1.0, 1.0, 1.0,
                          0.956, -0.272, -1.106,
                          0.621, -0.647, 1.703);
  vec3 yiq = toYIQ * col;
  float ca = cos(a), sa = sin(a);
  yiq = vec3(yiq.x, yiq.y * ca - yiq.z * sa, yiq.y * sa + yiq.z * ca);
  return toRGB * yiq;
}

vec3 shade(vec2 uv, vec2 p, float t) {
  vec2 q = p * 1.6;
  float amp = 0.25 + u_intensity * 0.85;
  for (float i = 1.0; i < 5.0; i += 1.0) {
    q.x += amp / i * cos(i * 2.4 * q.y + t * 0.8 + u_seed);
    q.y += amp / i * cos(i * 1.7 * q.x + t * 0.6);
  }
  return palette(0.5 + 0.5 * sin(q.x + q.y));
}

void main() {
  vec2 uv = gl_FragCoord.xy / u_resolution.xy;
  vec2 screenUv = uv;
  vec2 p = (gl_FragCoord.xy - 0.5 * u_resolution.xy)
    / min(u_resolution.x, u_resolution.y);
  float cursorMask = 0.0;

  if (u_cursorPresence > 0.001) {
    vec2 cursor = (0.5 * u_mouse * u_resolution.xy)
      / min(u_resolution.x, u_resolution.y);
    vec2 cursorDelta = p - cursor;
    if (u_cursorEffect < 0.5) {
      p += cursor * u_cursorPresence * u_cursorStrength * 0.55;
    } else {
      float cursorDistance = length(cursorDelta);
      vec2 cursorDirection = cursorDelta / max(cursorDistance, 0.0001);
      cursorMask = u_cursorPresence
        * (1.0 - smoothstep(0.0, u_cursorRadius, cursorDistance));
      if (u_cursorEffect < 1.5) {
        p -= cursorDirection * cursorMask * u_cursorStrength * 0.24;
      } else if (u_cursorEffect < 2.5) {
        float cursorAngle = cursorMask * u_cursorStrength * 2.2;
        float cc = cos(cursorAngle), cs = sin(cursorAngle);
        p = cursor + mat2(cc, -cs, cs, cc) * cursorDelta;
      } else if (u_cursorEffect < 3.5) {
        float ripple = sin(
          cursorDistance / max(u_cursorRadius, 0.001) * 18.0 - u_time * 5.0);
        p -= cursorDirection * ripple * cursorMask * u_cursorStrength * 0.07;
      }
    }
  }

  uv = p * min(u_resolution.x, u_resolution.y) / u_resolution.xy + 0.5;
  p *= u_scale;
  if (abs(u_rotate) > 0.0001) {
    float cr = cos(u_rotate), sr = sin(u_rotate);
    p = mat2(cr, -sr, sr, cr) * p;
  }
  p += u_offset;
  if (u_drift > 0.0001)
    p += u_drift * vec2(sin(u_time * 0.31), cos(u_time * 0.23));
  if (u_warp > 0.0) {
    p += u_warp * (vec2(
      fbm(p * u_detail + u_seed),
      fbm(p * u_detail + vec2(5.2, 1.3))) - 0.5);
  }
  vec3 col;
  if (u_blur > 0.0) {
    float e = u_blur;
    float pe = e * u_scale;
    vec2 uvE = vec2(e) * min(u_resolution.x, u_resolution.y) / u_resolution.xy;
    col  = shade(uv, p, u_time) * 0.36;
    col += shade(uv + vec2(uvE.x, 0.0), p + vec2(pe, 0.0), u_time) * 0.16;
    col += shade(uv - vec2(uvE.x, 0.0), p - vec2(pe, 0.0), u_time) * 0.16;
    col += shade(uv + vec2(0.0, uvE.y), p + vec2(0.0, pe), u_time) * 0.16;
    col += shade(uv - vec2(0.0, uvE.y), p - vec2(0.0, pe), u_time) * 0.16;
  } else {
    col = shade(uv, p, u_time);
  }
  if (abs(u_contrast - 1.0) > 0.0001)
    col = (col - 0.5) * u_contrast + 0.5;
  if (abs(u_saturation - 1.0) > 0.0001) {
    float luma = dot(col, vec3(0.299, 0.587, 0.114));
    col = mix(vec3(luma), col, u_saturation);
  }
  if (abs(u_hue) > 0.0001)
    col = hueRotate(col, u_hue);
  if (abs(u_brightness) > 0.0001)
    col += u_brightness;
  if (u_vignette > 0.0001) {
    float vd = length(screenUv - 0.5) * 1.41421356;
    col *= 1.0 - u_vignette * smoothstep(0.35, 1.0, vd);
  }
  if (u_cursorPresence > 0.001 && u_cursorEffect > 3.5)
    col += (vec3(0.18) + col * 0.12) * cursorMask * u_cursorStrength;
  if (u_grain > 0.0001)
    col += (grainHash(
      gl_FragCoord.xy + vec2(u_seed * 17.0, u_seed * 31.0)) - 0.5) * u_grain;
  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
`;

// CodeBeast AI Signature Obsidian & Neon-Orange Color Palette (Normalized 0.0 - 1.0)
const UNIFORMS = {
  colors: [
    [0.031, 0.015, 0.008], // #080402 Base Deep Obsidian
    [0.878, 0.478, 0.282], // #E07A48 Burnt Copper Wave
    [1.0, 0.549, 0.259],   // #FF8C42 Neon Amber Light
    [0.18, 0.07, 0.03],    // #2E1208 Deep Obsidian Shadow
    [0.05, 0.027, 0.015],  // #0D0704 Midnight Black
    [0.639, 0.251, 0.082], // #A34015 Fiery Ember Copper
    [0.451, 0.176, 0.059], // #732D0F Warm Atmospheric Halo
    [1.0, 0.941, 0.839],   // #FFF0D6 Cream Amber Highlight
  ] as [number, number, number][],
  colorCount: 6,
  scale: 1.94,
  intensity: 0.58,
  paramA: 0.48,
  warp: 0.042,
  detail: 2.976,
  contrast: 1.311,
  brightness: -0.02,
  saturation: 1.05,
  hue: 0.0,
  vignette: 0.25,
  blur: 0.0012,
  grain: 0.007,
  seed: 3195.0,
  rotate: 4.3284,
  offsetX: -0.1,
  offsetY: 0.02,
  drift: 0.06,
  cursorEnabled: true,
  cursorEffect: 2.0,
  cursorStrength: 0.65,
  cursorRadius: 0.46,
  oklab: 1.0,
  timeScale: 0.35,
};

const pendingContextReleases = new WeakMap<HTMLCanvasElement, number>();

export function ShaderBackground({ className }: { className?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [canvasKey, setCanvasKey] = useState(0);
  const pathname = usePathname();

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const cvs = canvas;
    const pendingRelease = pendingContextReleases.get(cvs);
    if (pendingRelease !== undefined) window.clearTimeout(pendingRelease);
    pendingContextReleases.delete(cvs);

    let glCtx: WebGLRenderingContext | null = null;
    let loseExt: any = null;
    let program: WebGLProgram | null = null;
    let buf: WebGLBuffer | null = null;
    let loc = -1;
    let uni: {
      colors: WebGLUniformLocation | null;
      scene: WebGLUniformLocation | null;
      shape: WebGLUniformLocation | null;
      surface: WebGLUniformLocation | null;
      finish: WebGLUniformLocation | null;
      transform: WebGLUniformLocation | null;
      space: WebGLUniformLocation | null;
      cursor: WebGLUniformLocation | null;
    } = {
      colors: null,
      scene: null,
      shape: null,
      surface: null,
      finish: null,
      transform: null,
      space: null,
      cursor: null,
    };

    let targetX = 0;
    let targetY = 0;
    let targetPresence = 0;
    let mouseX = 0;
    let mouseY = 0;
    let cursorPresence = 0;
    let pointerKnown = false;
    let pointerClientX = 0;
    let pointerClientY = 0;
    let bounds = cvs.getBoundingClientRect();
    let raf = 0;
    let lastNow: number | null = null;
    let disposed = false;
    const start = performance.now();
    const timeAnimated = Math.abs(UNIFORMS.timeScale) > 0.0001;

    const resizeCanvas = () => {
      if (!cvs || disposed) return;
      const b = cvs.getBoundingClientRect();
      const w = b.width > 50 ? b.width : (window.innerWidth || 1920);
      const h = b.height > 50 ? b.height : (window.innerHeight || 1080);
      const dpr = Math.min(window.devicePixelRatio || 1, 1.25);
      const rawWidth = Math.max(100, Math.round(w * dpr));
      const rawHeight = Math.max(100, Math.round(h * dpr));
      const pixelScale = Math.min(
        1,
        Math.sqrt(1_200_000 / Math.max(1, rawWidth * rawHeight))
      );
      const width = Math.max(100, Math.round(rawWidth * pixelScale));
      const height = Math.max(100, Math.round(rawHeight * pixelScale));
      if (cvs.width !== width || cvs.height !== height) {
        cvs.width = width;
        cvs.height = height;
      }
      if (glCtx && !glCtx.isContextLost()) {
        try {
          glCtx.viewport(0, 0, width, height);
        } catch {
          // ignore
        }
      }
    };

    const uploadStaticUniforms = () => {
      if (!glCtx || !program || glCtx.isContextLost()) return;
      try {
        glCtx.useProgram(program);
        if (uni.colors) glCtx.uniform3fv(uni.colors, new Float32Array(UNIFORMS.colors.flat()));
        if (uni.shape) glCtx.uniform4f(uni.shape, UNIFORMS.scale, UNIFORMS.intensity, UNIFORMS.paramA, UNIFORMS.warp);
        if (uni.surface) glCtx.uniform4f(uni.surface, UNIFORMS.detail, UNIFORMS.contrast, UNIFORMS.brightness, UNIFORMS.saturation);
        if (uni.finish) glCtx.uniform4f(uni.finish, UNIFORMS.hue, UNIFORMS.vignette, UNIFORMS.blur, UNIFORMS.grain);
        if (uni.transform) glCtx.uniform4f(uni.transform, UNIFORMS.seed, UNIFORMS.rotate, UNIFORMS.drift, UNIFORMS.oklab);
        if (uni.cursor) glCtx.uniform4f(uni.cursor, 0, UNIFORMS.cursorEffect, UNIFORMS.cursorStrength, UNIFORMS.cursorRadius);
      } catch {
        // ignore
      }
    };

    const setupWebGL = () => {
      if (disposed || !cvs) return false;
      try {
        if (!glCtx || glCtx.isContextLost()) {
          glCtx = (cvs.getContext("webgl", {
            antialias: false,
            powerPreference: "default",
            preserveDrawingBuffer: false,
          }) || cvs.getContext("experimental-webgl")) as WebGLRenderingContext | null;
        }
        if (!glCtx || glCtx.isContextLost()) {
          return false;
        }

        try {
          loseExt = glCtx.getExtension("WEBGL_lose_context");
        } catch {
          // ignore
        }

        const compile = (type: number, src: string) => {
          const s = glCtx!.createShader(type);
          if (!s) return null;
          glCtx!.shaderSource(s, src);
          glCtx!.compileShader(s);
          if (!glCtx!.getShaderParameter(s, glCtx!.COMPILE_STATUS)) {
            glCtx!.deleteShader(s);
            return null;
          }
          return s;
        };

        const vertexShader = compile(glCtx.VERTEX_SHADER, VERT);
        const fragmentShader = compile(glCtx.FRAGMENT_SHADER, FRAG);
        if (!vertexShader || !fragmentShader) return false;

        const prog = glCtx.createProgram();
        if (!prog) return false;
        glCtx.attachShader(prog, vertexShader);
        glCtx.attachShader(prog, fragmentShader);
        glCtx.linkProgram(prog);
        glCtx.deleteShader(vertexShader);
        glCtx.deleteShader(fragmentShader);

        if (!glCtx.getProgramParameter(prog, glCtx.LINK_STATUS)) {
          glCtx.deleteProgram(prog);
          return false;
        }

        program = prog;
        glCtx.useProgram(program);

        buf = glCtx.createBuffer();
        glCtx.bindBuffer(glCtx.ARRAY_BUFFER, buf);
        glCtx.bufferData(
          glCtx.ARRAY_BUFFER,
          new Float32Array([-1, -1, 3, -1, -1, 3]),
          glCtx.STATIC_DRAW
        );

        loc = glCtx.getAttribLocation(program, "a_position");
        if (loc !== -1) {
          glCtx.enableVertexAttribArray(loc);
          glCtx.vertexAttribPointer(loc, 2, glCtx.FLOAT, false, 0, 0);
        }

        uni = {
          colors: glCtx.getUniformLocation(program, "u_colors"),
          scene: glCtx.getUniformLocation(program, "u_scene"),
          shape: glCtx.getUniformLocation(program, "u_shape"),
          surface: glCtx.getUniformLocation(program, "u_surface"),
          finish: glCtx.getUniformLocation(program, "u_finish"),
          transform: glCtx.getUniformLocation(program, "u_transform"),
          space: glCtx.getUniformLocation(program, "u_space"),
          cursor: glCtx.getUniformLocation(program, "u_cursor"),
        };

        uploadStaticUniforms();
        resizeCanvas();
        return true;
      } catch {
        return false;
      }
    };

    function requestRender() {
      if (!disposed && raf === 0) {
        raf = requestAnimationFrame(render);
      }
    }

    const updatePointerTarget = () => {
      if (!pointerKnown || !cvs) return;
      bounds = cvs.getBoundingClientRect();
      if (bounds.width === 0 || bounds.height === 0) return;
      const inside =
        pointerClientX >= bounds.left &&
        pointerClientX <= bounds.right &&
        pointerClientY >= bounds.top &&
        pointerClientY <= bounds.bottom;
      if (!inside) {
        targetPresence = 0;
        requestRender();
        return;
      }
      const nextX = ((pointerClientX - bounds.left) / bounds.width) * 2 - 1;
      const nextY = -(((pointerClientY - bounds.top) / bounds.height) * 2 - 1);
      if (targetPresence === 0 && cursorPresence < 0.01) {
        mouseX = nextX;
        mouseY = nextY;
      }
      targetX = nextX;
      targetY = nextY;
      targetPresence = 1;
      requestRender();
    };

    const onPointerMove = (event: PointerEvent) => {
      pointerKnown = true;
      pointerClientX = event.clientX;
      pointerClientY = event.clientY;
      updatePointerTarget();
    };

    const onPointerLeave = () => {
      pointerKnown = false;
      targetPresence = 0;
      requestRender();
    };

    const updateLayout = () => {
      if (!cvs || disposed) return;
      bounds = cvs.getBoundingClientRect();
      resizeCanvas();
      updatePointerTarget();
      requestRender();
    };

    const onScrollThrottled = () => {
      if (!cvs || disposed) return;
      bounds = cvs.getBoundingClientRect();
      updatePointerTarget();
    };

    const onContextLost = (e: Event) => {
      e.preventDefault();
      if (raf !== 0) {
        cancelAnimationFrame(raf);
        raf = 0;
      }
      lastNow = null;
      try {
        if (loseExt) {
          window.setTimeout(() => {
            if (!disposed) {
              loseExt.restoreContext();
            }
          }, 40);
        }
      } catch {
        // ignore
      }
      window.setTimeout(() => {
        if (!disposed && (!glCtx || glCtx.isContextLost())) {
          setCanvasKey((k) => k + 1);
        }
      }, 150);
    };

    const onContextRestored = () => {
      if (disposed) return;
      if (setupWebGL()) {
        lastNow = null;
        requestRender();
      } else {
        setCanvasKey((k) => k + 1);
      }
    };

    cvs.addEventListener("webglcontextlost", onContextLost);
    cvs.addEventListener("webglcontextrestored", onContextRestored);

    window.addEventListener("resize", updateLayout, { passive: true });
    window.addEventListener("popstate", updateLayout, { passive: true });
    window.addEventListener("focus", updateLayout, { passive: true });
    window.addEventListener("pageshow", updateLayout, { passive: true });
    if (UNIFORMS.cursorEnabled) {
      window.addEventListener("pointermove", onPointerMove, { passive: true });
      window.addEventListener("pointercancel", onPointerLeave, { passive: true });
      window.addEventListener("scroll", onScrollThrottled, { passive: true });
      window.addEventListener("blur", onPointerLeave);
      document.documentElement.addEventListener("pointerleave", onPointerLeave);
    }

    const onVisibilityChange = () => {
      if (!document.hidden && !disposed) {
        updateLayout();
        if (!glCtx || glCtx.isContextLost() || !program) {
          if (!setupWebGL()) {
            setCanvasKey((k) => k + 1);
          }
        }
        lastNow = null;
        requestRender();
      }
    };
    document.addEventListener("visibilitychange", onVisibilityChange);

    const resizeObserver = new ResizeObserver(updateLayout);
    resizeObserver.observe(cvs);

    if (!setupWebGL()) {
      window.setTimeout(() => {
        if (!disposed) setCanvasKey((k) => k + 1);
      }, 100);
    }

    const keepaliveInterval = window.setInterval(() => {
      if (disposed || !cvs) return;
      if (glCtx && glCtx.isContextLost()) {
        try {
          if (loseExt) loseExt.restoreContext();
          else setCanvasKey((k) => k + 1);
        } catch {
          setCanvasKey((k) => k + 1);
        }
      } else if (!glCtx || !program) {
        if (!setupWebGL()) {
          setCanvasKey((k) => k + 1);
        }
      } else if (raf === 0) {
        lastNow = null;
        requestRender();
      }
    }, 600);

    function render(now: number) {
      raf = 0;
      if (disposed || !cvs) return;
      if (!glCtx || glCtx.isContextLost() || !program) {
        if (!setupWebGL()) {
          setCanvasKey((k) => k + 1);
          return;
        }
      }
      try {
        const dt = lastNow === null ? 0 : Math.min((now - lastNow) / 1000, 0.1);
        lastNow = now;
        const follow = 1 - Math.exp(-12 * dt);
        mouseX += (targetX - mouseX) * follow;
        mouseY += (targetY - mouseY) * follow;
        cursorPresence += (targetPresence - cursorPresence) * follow;
        
        const width = cvs.width;
        const height = cvs.height;

        glCtx.useProgram(program);
        if (uni.scene) {
          glCtx.uniform4f(
            uni.scene,
            width,
            height,
            ((now - start) / 1000) * UNIFORMS.timeScale,
            UNIFORMS.colorCount
          );
        }
        if (uni.space) {
          glCtx.uniform4f(
            uni.space,
            UNIFORMS.offsetX,
            UNIFORMS.offsetY,
            mouseX,
            mouseY
          );
        }
        if (uni.cursor) {
          glCtx.uniform4f(
            uni.cursor,
            UNIFORMS.cursorEnabled ? cursorPresence : 0,
            UNIFORMS.cursorEffect,
            UNIFORMS.cursorStrength,
            UNIFORMS.cursorRadius
          );
        }
        glCtx.drawArrays(glCtx.TRIANGLES, 0, 3);
        const pointerSettling =
          Math.abs(targetX - mouseX) > 0.001 ||
          Math.abs(targetY - mouseY) > 0.001 ||
          Math.abs(targetPresence - cursorPresence) > 0.001;
        if (timeAnimated || pointerSettling) requestRender();
        else lastNow = null;
      } catch {
        lastNow = null;
      }
    }

    requestRender();

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      window.clearInterval(keepaliveInterval);
      resizeObserver.disconnect();
      document.removeEventListener("visibilitychange", onVisibilityChange);
      cvs.removeEventListener("webglcontextlost", onContextLost);
      cvs.removeEventListener("webglcontextrestored", onContextRestored);
      window.removeEventListener("resize", updateLayout);
      window.removeEventListener("popstate", updateLayout);
      window.removeEventListener("focus", updateLayout);
      window.removeEventListener("pageshow", updateLayout);
      if (UNIFORMS.cursorEnabled) {
        window.removeEventListener("pointermove", onPointerMove);
        window.removeEventListener("pointercancel", onPointerLeave);
        window.removeEventListener("scroll", onScrollThrottled);
        window.removeEventListener("blur", onPointerLeave);
        document.documentElement.removeEventListener(
          "pointerleave",
          onPointerLeave
        );
      }
      try {
        if (buf && glCtx && !glCtx.isContextLost()) glCtx.deleteBuffer(buf);
        if (program && glCtx && !glCtx.isContextLost()) glCtx.deleteProgram(program);
      } catch {
        // ignore WebGL disposal error
      }
    };
  }, [canvasKey]);

  // Route change watchdog: trigger layout and render verification when returning to route
  useEffect(() => {
    if (canvasRef.current) {
      window.dispatchEvent(new Event("resize"));
    }
  }, [pathname]);

  return (
    <canvas
      key={canvasKey}
      ref={canvasRef}
      className={className}
      style={{ display: "block", width: "100%", height: "100%", backgroundColor: "transparent", transition: "opacity 0.2s ease" }}
    />
  );
}

